import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {openDatabase,refreshTestWindows,login,dispatch,actorTransaction,ids} from './database.mjs';
const directory=resolve('.artifacts','physix-check-'+Date.now());mkdirSync(directory,{recursive:true});
const evidence=resolve('docs/physix/evidence/persistence-20260919');mkdirSync(evidence,{recursive:true});
const checks=[];let pg;
const pass=name=>{checks.push({name,passed:true});console.log('PASS',name);};
const deny=(promise,codes=['42501','P0002'])=>assert.rejects(promise,error=>codes.includes(error.code));
try{
 pg=await openDatabase(resolve(directory,'pgdata'));await refreshTestWindows(pg);
 const patient=await login(pg,'patient'),other=await login(pg,'other'),staff=await login(pg,'practitioner');
 const run=(token,action,payload,commandId=randomUUID())=>dispatch(pg,token,'command',{action,payload,commandId});
 let me=await dispatch(pg,patient.token,'me');
 assert.equal(me.relationship.workouts.length,3);assert.equal(me.relationship.sessions.length,0);assert.equal(me.relationship.entitlements[0].source,'complimentary');pass('Versioned assigned sessions load without fake purchases or history');
 assert.equal((await dispatch(pg,other.token,'me')).relationship.workouts.length,0);pass('Second patient starts with an honest empty plan');
 await deny(dispatch(pg,'','me'),['28000']);pass('Missing account session is denied');
 const scheduled=me.relationship.workouts.find(w=>w.prescription.dayOffset===0),exercise=scheduled.prescription.exercises[0];
 const key=randomUUID(),start=await run(patient.token,'care.start',{scheduledId:scheduled.id},key);
 assert.deepEqual(await run(patient.token,'care.start',{scheduledId:scheduled.id},key),start);pass('Lost-response start retry returns the same persisted attempt');
 await deny(run(patient.token,'care.start',{scheduledId:scheduled.id}),['23505']);pass('Only one open attempt exists for a scheduled session');
 await deny(dispatch(pg,other.token,'session',{id:start.id}));await deny(run(other.token,'care.save-set',{sessionId:start.id,exerciseId:exercise.id,setIndex:0,revision:0,actualReps:9,loadKg:null,durationSeconds:null,distanceM:null,skipped:false}));pass('Sibling patient cannot read or change the attempt');
 const raw=await actorTransaction(pg,other.token,tx=>tx.query('select * from public.workout_sessions where id=$1',[start.id]));assert.equal(raw.rows.length,0);pass('Direct table read enforces row-level isolation');
 await deny(run(patient.token,'care.transition',{sessionId:start.id,revision:0,state:'completed'}),['22023']);pass('Empty attempt cannot be marked complete');
 const actual={sessionId:start.id,exerciseId:exercise.id,setIndex:0,revision:0,actualReps:8,loadKg:null,durationSeconds:null,distanceM:null,skipped:false},saveKey=randomUUID();
 const saved=await run(patient.token,'care.save-set',actual,saveKey);assert.deepEqual(await run(patient.token,'care.save-set',actual,saveKey),saved);pass('Set save retries are idempotent');
 await deny(run(patient.token,'care.save-set',{...actual,actualReps:7},saveKey),['40001']);pass('Reusing a command ID with changed actuals is rejected');
 const detail=await dispatch(pg,patient.token,'session',{id:start.id});assert.equal(detail.sets[0].actual_reps,8);assert.equal(detail.sets.length,1);pass('Only the acknowledged actual set is recorded');
 const pause=await run(patient.token,'care.transition',{sessionId:start.id,revision:0,state:'paused'});let paused=await dispatch(pg,patient.token,'session',{id:start.id});assert.equal(paused.session.running_since,null);assert.equal(paused.session.state,'paused');pass('Pause stores elapsed time and stops the running clock');
 await deny(run(patient.token,'care.transition',{sessionId:start.id,revision:0,state:'in_progress'}),['40001']);pass('Stale session revision is rejected');
 await pg.close();pg=await openDatabase(resolve(directory,'pgdata'));
 const reopened=await dispatch(pg,patient.token,'session',{id:start.id});assert.equal(reopened.sets[0].actual_reps,8);assert.equal(reopened.session.state,'paused');pass('Session, set, identity and pause survive database close and reopen');
 const resumed=await run(patient.token,'care.transition',{sessionId:start.id,revision:pause.revision,state:'in_progress'});
 const finishKey=randomUUID(),finished=await run(patient.token,'care.transition',{sessionId:start.id,revision:resumed.revision,state:'completed'},finishKey);
 assert.deepEqual(await run(patient.token,'care.transition',{sessionId:start.id,revision:resumed.revision,state:'completed'},finishKey),finished);pass('Completion retry does not create a duplicate record');
 await deny(run(patient.token,'care.save-set',{...actual,revision:1,actualReps:11}));pass('Completed actuals cannot be silently rewritten');
 const second=await run(patient.token,'care.start',{scheduledId:scheduled.id});assert.notEqual(second.id,start.id);me=await dispatch(pg,patient.token,'me');assert.equal(me.relationship.sessions.length,2);pass('A genuine repeat has a separate attempt and preserves old history');
 const staffView=await dispatch(pg,staff.token,'session',{id:start.id});assert.equal(staffView.editable,false);assert.equal(staffView.sets[0].actual_reps,8);pass('Assigned practitioner can read but cannot overwrite patient actuals');
 await deny(run(staff.token,'care.save-set',{...actual,actualReps:12}));pass('Practitioner mutation of patient actuals is denied');
 await deny(actorTransaction(pg,patient.token,tx=>tx.query("update public.program_versions set title='Changed'")));pass('Patient cannot alter published programme versions directly');
 const week=new Date();week.setUTCHours(0,0,0,0);week.setUTCDate(week.getUTCDate()-(week.getUTCDay()+6)%7);
 const checkin={relationshipId:ids.relationship,weekStart:week.toISOString().slice(0,10),difficulty:4,body:'Synthetic local check-in'};
 await deny(run(patient.token,'care.check-in',checkin),['22023']);pass('Check-in sharing requires explicit acknowledgement');
 await run(patient.token,'care.check-in',{...checkin,shared:true});assert.equal((await dispatch(pg,patient.token,'me')).relationship.check_ins.length,1);assert.equal((await dispatch(pg,other.token,'me')).relationship.check_ins.length,0);pass('Shared check-in persists only within its relationship');
 const offers=await dispatch(pg,'','offers');assert.equal(offers.length,3);assert.deepEqual(Object.keys(offers[0]).sort(),['duration_minutes','id','modes','name']);pass('Public catalogue exposes only public fields');
 const day=new Date(Date.now()+86400000).toISOString().slice(0,10),offerId=offers[0].id;
 const slots=await dispatch(pg,'','slots',{offerId,mode:'in_clinic',day});assert.ok(slots.length>2);assert.equal(slots[0].startsAt.slice(11,16),'09:00');assert.deepEqual(Object.keys(slots[0]).sort(),['endsAt','startsAt','timezone']);pass('Availability reveals no patient identity or private calendar fields');
 const payload={offerId,mode:'in_clinic',startsAt:slots[0].startsAt},bookingKey=randomUUID();
 const race=await Promise.allSettled([run(patient.token,'booking.reserve',payload,bookingKey),run(other.token,'booking.reserve',payload)]);
 assert.equal(race.filter(r=>r.status==='fulfilled').length,1);assert.equal(race[0].status,'fulfilled');const booking=race[0].value;pass('Concurrent local requests for the last time produce one reservation');
 assert.deepEqual(await run(patient.token,'booking.reserve',payload,bookingKey),booking);pass('Reservation retry returns the original booking');
 await deny(run(other.token,'booking.reserve',{...payload,startsAt:slots[1].startsAt}),['23P01']);pass('Overlapping appointment at a different start time is rejected by PostgreSQL');
 await deny(run(other.token,'booking.cancel',{id:booking.id}));assert.equal((await dispatch(pg,other.token,'me')).appointments.length,0);pass('Another patient cannot read or cancel the reservation');
 await pg.close();pg=await openDatabase(resolve(directory,'pgdata'));assert.equal((await dispatch(pg,patient.token,'me')).appointments[0].id,booking.id);pass('Appointment survives database restart');
 await run(patient.token,'booking.cancel',{id:booking.id});assert.equal((await dispatch(pg,patient.token,'me')).appointments[0].state,'cancelled');const again=await dispatch(pg,'','slots',{offerId,mode:'in_clinic',day});assert.ok(again.some(s=>s.startsAt===payload.startsAt));pass('Cancellation retains history and releases the allocated time');
 await dispatch(pg,patient.token,'logout');await deny(dispatch(pg,patient.token,'me'),['28000']);pass('Server session revocation prevents later data access');
 console.log('LOCAL_POSTGRES_CHECKS_PASSED',checks.length);
 writeFileSync(resolve(evidence,'database-checks.json'),JSON.stringify({checkedAt:new Date().toISOString(),checks,passed:true,engine:'PGlite local PostgreSQL; synthetic provider-shaped auth, not Supabase Auth',concurrency:'Concurrent API dispatches are serialized by the single local database process; multi-connection production stress remains untested'},null,2));
}catch(error){writeFileSync(resolve(evidence,'database-checks.json'),JSON.stringify({checks,passed:false,error:{name:error.name,code:error.code,message:error.message}},null,2));console.error(error);process.exitCode=1;}
finally{if(pg)await pg.close();}
