"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Check,ChevronLeft,ChevronRight,List,Pause,Play,Video,X} from 'lucide-react';
import type {PlanSet,SessionDetail,SetLog,SessionState} from '@/shared/gymaf/contracts';
import {elapsedSeconds} from '@/shared/gymaf/validation';
import {Shell} from './shell';
import {Row,Sheet} from './ui';
import {SavedPending} from './local-patient';
import {useSavedCommand,useSavedResource} from './local-api';
function ActualSet({sessionId,exerciseId,index,target,saved,editable,onDirty,onSaved}:{sessionId:string;exerciseId:string;index:number;target:PlanSet;saved?:SetLog;editable:boolean;onDirty:(dirty:boolean)=>void;onSaved:()=>void}){
 const mutation=useSavedCommand();
 const [values,setValues]=useState({actualReps:saved?.actual_reps??'',loadKg:saved?.load_kg??'',durationSeconds:saved?.duration_seconds??'',distanceM:saved?.distance_m??''});
 const [skipped,setSkipped]=useState(saved?.skipped||false),[dirty,setDirty]=useState(false),[notice,setNotice]=useState('');
 const fields=[['actualReps','Repetitions',target.reps,1000],['durationSeconds','Seconds',target.durationSeconds,86400],['loadKg','Resistance · kg',target.loadKg,1000],['distanceM','Distance · m',target.distanceM,1000000]] as const;
 function changed(){setDirty(true);onDirty(true);setNotice('');}
 async function save(){
  const actual=Object.fromEntries(Object.entries(values).map(([key,value])=>[key,skipped||value===''?null:Number(value)]));
  const result=await mutation.run('care.save-set',{sessionId,exerciseId,setIndex:index,revision:saved?.revision||0,...actual,skipped});
  if(result){setDirty(false);onDirty(false);setNotice('Saved');onSaved();}
 }
 return <form className="px-actual-set" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={!editable||mutation.busy}><legend>Set {index+1}{saved&&!dirty?<span><Check size={14}/>{saved.skipped?'Skipped':'Saved'}</span>:null}</legend><div className="px-actual-fields">{fields.filter(([, ,planned])=>planned!==null).map(([key,label,planned,max])=><label key={key}>{label}<input aria-label={'Set '+(index+1)+' '+label} type="number" inputMode={key==='actualReps'?'numeric':'decimal'} min="0" max={max} step={key==='actualReps'?'1':'any'} disabled={skipped} value={values[key]} placeholder={String(planned)} onChange={e=>{setValues(v=>({...v,[key]:e.target.value}));changed();}}/><small>Target {planned}</small></label>)}</div><div className="px-actual-actions"><label><input type="checkbox" checked={skipped} onChange={e=>{setSkipped(e.target.checked);changed();}}/>Skip this set</label><button className="button" disabled={!dirty||mutation.busy}>{mutation.busy?'Saving…':'Save set'}</button></div></fieldset>{dirty&&<p className="px-note">Not saved yet.</p>}{notice&&<p className="px-note" role="status">{notice}</p>}{mutation.error&&<p className="px-error" role="alert">{mutation.error}</p>}</form>;
}
export function LocalSession({id}:{id:string}){
 const resource=useSavedResource<SessionDetail>('sessions/'+id),mutation=useSavedCommand(),router=useRouter();
 const [index,setIndex]=useState(0),[now,setNow]=useState(0),[sheet,setSheet]=useState(''),[dirty,setDirty]=useState<Set<string>>(new Set());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!dirty.size)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty.size]);
 if(!resource.data)return <Shell local><SavedPending error={resource.error} reload={resource.reload}/></Shell>;
 const {session,sets,editable}=resource.data,exercises=session.prescription.exercises,exercise=exercises[index];
 const finished=['completed','abandoned'].includes(session.state),total=exercises.reduce((n,e)=>n+e.sets.length,0),elapsed=elapsedSeconds(session,now||Date.parse(session.started_at));
 const performed=sets.some(s=>!s.skipped&&((s.actual_reps||0)>0||(s.duration_seconds||0)>0||(s.distance_m||0)>0));
 async function change(state:SessionState,leave=false){if(dirty.size)return;const result=await mutation.run('care.transition',{sessionId:id,revision:session.revision,state});if(result){setSheet('');if(leave)router.push('/app');else resource.reload();}}
 if(finished)return <Shell local><div className="px-care-heading"><p className="px-eyebrow">Saved session</p><h1>{session.state==='completed'?'Session finished.':'Session stopped.'}</h1><p>{session.prescription.title} · {Math.floor(elapsed/60)} min {elapsed%60}s</p></div><div className="px-care-stats"><div><strong>{sets.filter(s=>!s.skipped).length}</strong><span>Sets recorded</span></div><div><strong>{sets.filter(s=>s.skipped).length}</strong><span>Skipped</span></div><div><strong>{total-sets.length}</strong><span>Unrecorded</span></div></div><div className="row-group">{exercises.map(e=><section className="px-care-appointment" key={e.id}><h2>{e.name}</h2>{e.sets.map((_,n)=>{const s=sets.find(s=>s.exercise_id===e.id&&s.set_index===n);return <p key={n}>Set {n+1} · {!s?'Not recorded':s.skipped?'Skipped':[s.actual_reps!==null?s.actual_reps+' reps':'',s.duration_seconds!==null?s.duration_seconds+' sec':'',s.load_kg!==null?s.load_kg+' kg':'',s.distance_m!==null?s.distance_m+' m':''].filter(Boolean).join(' · ')||'No actuals entered'}</p>;})}</section>)}</div><Link className="button primary full" href="/app/progress">View saved history<ChevronRight size={18}/></Link><Link className="button full" href={'/app/plans/'+session.scheduled_workout_id}>Back to plan</Link></Shell>;
 return <Shell local focused><div className="px-player"><header className="px-player-top"><button className="px-circle" aria-label="Leave session" onClick={()=>setSheet('Leave session')}><X size={22}/></button><div><p>{session.prescription.title}</p><div className="px-progress-track" role="progressbar" aria-label="Sets logged" aria-valuemin={0} aria-valuemax={total} aria-valuenow={sets.length}><span style={{width:sets.length/total*100+'%'}}/></div><small>{sets.length} of {total} sets logged</small></div><button className="px-circle" aria-label={session.state==='in_progress'?'Pause session':'Resume session'} disabled={mutation.busy||resource.loading||!!dirty.size} onClick={()=>void change(session.state==='in_progress'?'paused':'in_progress')}>{session.state==='in_progress'?<Pause size={21}/>:<Play size={21}/>}</button></header><div className="px-player-media"><Video size={36}/><h2>Exercise instructions</h2><p>No instructional video supplied yet.</p><span>Local test content · not a prescription</span></div><section className="px-exercise-panel"><div className="px-player-meta"><span>EXERCISE {index+1} / {exercises.length}</span><button aria-label="Exercise list" disabled={!!dirty.size} onClick={()=>setSheet('Exercises')}><List size={21}/></button></div><h1>{exercise.name}</h1><p className="px-dosage">{exercise.sets.length} sets · sample dosage</p><div className="px-timer"><span>{Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,'0')}</span><small>{session.state==='paused'?'Paused':'Session time'}</small></div><p className="px-note px-instructions">{exercise.instructions}</p>{exercise.sets.map((target,n)=>{const saved=sets.find(s=>s.exercise_id===exercise.id&&s.set_index===n),key=exercise.id+':'+n;return <ActualSet key={key+':'+(saved?.revision||0)} sessionId={id} exerciseId={exercise.id} index={n} target={target} saved={saved} editable={editable&&session.state==='in_progress'&&!resource.loading} onDirty={value=>setDirty(prev=>{const next=new Set(prev);if(value)next.add(key);else next.delete(key);return next;})} onSaved={resource.reload}/>;})}
 {session.state==='paused'&&<button className="button primary full" disabled={mutation.busy} onClick={()=>void change('in_progress')}><Play size={18}/>Resume session</button>}
 <div className="px-player-actions"><button disabled={!index||!!dirty.size} onClick={()=>setIndex(i=>i-1)}><ChevronLeft size={18}/>Previous</button><button disabled={!!dirty.size} onClick={()=>index===exercises.length-1?setSheet('Finish session'):setIndex(i=>i+1)}>{index===exercises.length-1?'Finish session':'Next exercise'}<ChevronRight size={18}/></button></div>{dirty.size>0&&<p className="px-note">Save your changes before changing exercises or leaving.</p>}<button className="px-text-link" disabled={!!dirty.size} onClick={()=>setSheet('Finish session')}>Finish session</button>{mutation.error&&<p className="px-error" role="alert">{mutation.error}</p>}</section></div>
 {sheet&&<Sheet title={sheet} onClose={()=>setSheet('')}>{sheet==='Exercises'?<div className="row-group">{exercises.map((e,n)=><Row key={e.id} detail={e.sets.length+' sets'} onClick={()=>{setIndex(n);setSheet('');}}>{e.name}</Row>)}</div>:sheet==='Leave session'?<><p className="px-note">{dirty.size?'You have unsaved entries. Close this sheet and save them first.':'Pause and return later. Acknowledged sets and your session stay in the local database after a reload.'}</p><button className="button primary full" disabled={mutation.busy||!!dirty.size} onClick={()=>void change('paused',true)}>Pause & leave</button><button className="button full" onClick={()=>setSheet('')}>Keep going</button></>:<><p className="px-note">{sets.length<total?(total-sets.length)+' sets remain unrecorded. Finishing does not mark them performed.':'Your logged sets are saved.'}</p><button className="button primary full" disabled={!performed||!!dirty.size||mutation.busy} onClick={()=>void change('completed')}>{mutation.busy?'Saving…':'Finish & save session'}</button><button className="button full" disabled={!!dirty.size||mutation.busy} onClick={()=>void change('abandoned')}>Stop without completing</button>{!performed&&<p className="px-note">Record at least one performed set to finish, or stop without completing.</p>}</>}{mutation.error&&<p className="px-error" role="alert">{mutation.error}</p>}</Sheet>}
 </Shell>;
}
