"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,Check,ChevronRight,Layers,List,Pause,Play,RotateCcw,Video,X} from 'lucide-react';
import {Shell} from './shell';
import {Sheet,Row} from './ui';
import {useDemo} from './demo-context';
import {elapsedMs,examples,newAttempt,recordDemoSet,transition} from '@/shared/physix/demo';
/** Adapts Fidelity's focused player, set editor, pause, overview and finish controls.
 * No network/storage dependency: this is a labelled visual interaction proof. */
export function SessionDemo(){
 const {attempt,setAttempt,mode}=useDemo();const router=useRouter();
 const [index,setIndex]=useState(0),[reps,setReps]=useState('8'),[now,setNow]=useState(0),[sheet,setSheet]=useState(''),[error,setError]=useState(''),[failNext,setFailNext]=useState(false),[notice,setNotice]=useState('');
 const pending=useRef<{key:string;reps:number;command:string}|null>(null);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),300);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!Object.keys(attempt.actuals).length||attempt.status==='finished')return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[attempt.actuals,attempt.status]);
 const exercise=examples[index];const doneKeys=Object.keys(attempt.actuals);const nextSet=[1,2].find(i=>attempt.actuals[exercise.id+':'+i]===undefined);const seconds=Math.floor(elapsedMs(attempt,now||attempt.startedAt||0)/1000);const stopped=attempt.status!=='active';
 function change(to:'active'|'paused'|'finished'){try{const next=transition(attempt,to,Date.now());setAttempt(()=>next);setError('');if(to==='finished')setSheet('');}catch(e){setError(e instanceof Error?e.message:'Could not update this preview.');}}
 function record(){setNotice('');if(!nextSet||stopped)return;try{if(!reps.trim())throw new Error('Enter your repetitions.');const number=Number(reps);const key=exercise.id+':'+nextSet;const cmd=pending.current&&pending.current.key===key&&pending.current.reps===number?pending.current:{key,reps:number,command:crypto.randomUUID()};const next=recordDemoSet(attempt,cmd.key,cmd.reps,cmd.command);pending.current=cmd;if(failNext){setFailNext(false);throw new Error('Simulated save failure. Nothing was recorded. Retry to keep the same command.');}setAttempt(()=>next);pending.current=null;setError('');setNotice('Recorded in this demo only.');}catch(e){setError(e instanceof Error?e.message:'Could not record the set.');}}
 function leave(){change('paused');router.push('/dev/demo/plans/demo-plan');}
 if(mode==='empty'||mode==='pending')return <Shell demo preview><div className="px-empty"><Layers size={32}/><h1>No exercises assigned.</h1><p>This example state does not have a playable plan.</p><Link className="button" href="/dev/demo/plans">Back to My Plan</Link></div></Shell>;
 return <Shell demo preview focused><div className="px-player"><header className="px-player-top"><button className="px-circle" aria-label="Leave session" onClick={()=>setSheet('Leave session?')}><X size={22}/></button><div><p>YOUR MOVEMENT PLAN</p><div className="px-progress-track" role="progressbar" aria-label="Sets recorded in demo" aria-valuenow={doneKeys.length} aria-valuemin={0} aria-valuemax={6}><span style={{width:doneKeys.length/6*100+'%'}}/></div><small>{doneKeys.length} of 6 sets recorded</small></div><button className="px-circle" aria-label={attempt.status==='active'?'Pause demonstration':'Resume demonstration'} disabled={attempt.status==='finished'} onClick={()=>change(attempt.status==='active'?'paused':'active')}>{attempt.status==='active'?<Pause size={22}/>:<Play size={22}/>}</button></header>
 <div className="px-player-media"><Video size={42}/><h2>Exercise video</h2><p>Practitioner-approved media goes here.</p><span>Preview only · not exercise instruction</span></div>
 <section className="px-exercise-panel"><div className="px-player-meta"><span>EXERCISE {index+1} / {examples.length}</span><button onClick={()=>setSheet('Session overview')} aria-label="Exercise list"><List size={20}/></button></div><h1>{exercise.name}</h1><p className="px-dosage">Example dosage · {exercise.sets} sets × {exercise.reps} reps</p><div className="px-timer"><span>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</span><small>{attempt.status==='active'?'Session time':attempt.status==='finished'?'Demo finished':attempt.status==='paused'?'Paused':'Ready when you are'}</small></div>
 {attempt.status==='ready'?<button className="button primary full" onClick={()=>setAttempt(()=>transition(newAttempt(crypto.randomUUID()),'active',Date.now()))}><Play size={19}/>Start demonstration</button>:attempt.status==='paused'?<button className="button primary full" onClick={()=>change('active')}><Play size={19}/>Resume demonstration</button>:attempt.status==='finished'?<div className="px-demo-complete" role="status"><Check size={26}/><h2>Demonstration finished.</h2><p>Your example activity stays in this demo, not in a patient account.</p><Link href="/dev/demo/progress" className="button primary full">View demo activity<ChevronRight size={18}/></Link></div>:<><div className="px-set-row"><div><label htmlFor="actual-reps">Actual repetitions</label><small>Set {nextSet||2} of 2</small></div><input id="actual-reps" type="number" inputMode="numeric" min="0" max="999" step="1" value={reps} disabled={!nextSet} onChange={e=>{setReps(e.target.value);pending.current=null;setError('');}}/></div><div className="px-set-pills">{[1,2].map(n=><span key={n} className={attempt.actuals[exercise.id+':'+n]!==undefined?'recorded':''}>{attempt.actuals[exercise.id+':'+n]!==undefined?<Check size={15}/>:null}Set {n}{attempt.actuals[exercise.id+':'+n]!==undefined?' · '+attempt.actuals[exercise.id+':'+n]+' reps':''}</span>)}</div><button className="button primary full" onClick={record} disabled={!nextSet}>{nextSet?'Record set':'Both sets recorded'}<Check size={18}/></button></>}
 {error&&<p className="px-error" role="alert">{error}</p>}{notice&&!error&&<p className="px-record-notice" role="status">{notice}</p>}
 {attempt.status!=='finished'&&<><div className="px-player-actions"><button disabled={index===0} onClick={()=>{setIndex(i=>i-1);setError('');setNotice('');}}><ArrowLeft size={18}/>Previous</button><button onClick={()=>{if(index===2)setSheet('Finish demonstration');else{setIndex(i=>i+1);setError('');setNotice('');}}}>{index===2?'Finish':'Next exercise'}<ChevronRight size={18}/></button></div><details className="px-test-controls"><summary>Demo controls</summary><p>Nothing here sends an API request.</p><label><input type="checkbox" checked={failNext} onChange={e=>setFailNext(e.target.checked)}/>Simulate the next save failing</label><button onClick={()=>setSheet('Finish demonstration')}>End demonstration</button></details></>}
 </section></div>
 {sheet&&<Sheet title={sheet} onClose={()=>setSheet('')}>{sheet==='Session overview'?<div className="row-group">{examples.map((e,i)=><Row key={e.id} detail={'Example · '+e.sets+' sets'} onClick={()=>{setIndex(i);setSheet('');setError('');setNotice('');}}>{e.name}</Row>)}</div>:sheet==='Leave session?'?<><p className="px-note">Pause and return to your plan. This tab keeps the demonstration in memory; reloading or leaving the demo clears it.</p><button className="button primary full" onClick={leave}><Pause size={18}/>Pause & leave</button><button className="button full" onClick={()=>setSheet('')}>Keep going</button></>:<><p className="px-note">Only recorded example sets appear in demo activity. No real exercise session will be saved.</p><button className="button primary full" onClick={()=>change('finished')} disabled={!Object.values(attempt.actuals).some(n=>n>0)}>Finish demonstration<Check size={18}/></button>{!Object.values(attempt.actuals).some(n=>n>0)&&<p className="px-note">Record at least one performed set first, or leave without completion.</p>}<button className="button full" onClick={leave}><RotateCcw size={17}/>Leave without completing</button>{error&&<p role="alert">{error}</p>}</>}</Sheet>}
 </Shell>;
}